@startuml
|Автошкола|
start
:Запись ученика;
if (Ученик имеет права на все категории?) then (yes)
  :Зачисление на обучение;
  if (Обучение завершено?) then (yes)
    :Выдать свидетельство о праве;
  else (no)
    :Начало занятий;
    :Завершение обучения;
    :Выдать свидетельство о праве;
  endif
else (no)
  :Выбор категории;
  :Начало занятий;
  :Завершение обучения;
  :Выдать свидетельство о праве;
endif
stop
@enduml
