@startuml "A model of use cases describing business processes serving a driving school student"
title
Модель прецедентов, описывающих бизнес-процессы обслуживание ученика автошколы
end title

left to right direction
actor Ученик
actor Инструктор
actor Администратор
rectangle "Система автошколы" {
  (Регистрация) <-- Ученик
  (Запись на курсы) <-- Ученик
  (Оплата) <.. (Запись на курсы) : include
  (Выбор расписания) <-- Ученик
  (Назначение Инструктора) <-- Ученик
  (Начало курса) <-- Ученик
  (Оценивание успеваемости) <-- Инструктор
  (Обновление прогресса Ученика) <-- Инструктор
  (Управление курсами) <-- Администратор
  (Управление Инструкторами) <-- Администратор
  (Генерация отчетов) <-- Администратор
  (Регистрация) ..> (Управление курсами) : "только администратор"
  (Запись на курсы) ..> (Управление курсами) : "только администратор"
  (Назначение Инструктора) ..> (Управление Инструкторами) : "только администратор"
  (Оценивание успеваемости) ..> (Обновление прогресса Ученика) : "обновляет прогресс перед оцениванием"
  (Обновление прогресса Ученика) ..> (Генерация отчетов) : "только администратор"
}
@enduml
