@startuml
class Автоинструктор {
  - Имя: строка
  - Фамилия: строка
  - Стаж: число
  + ОтметитьНачалоЗанятия()
  + ОтметитьКонецЗанятия()
}

class Ученик {
  - Имя: строка
  - Фамилия: строка
  - Дата_рождения: дата
  - Категория: строка
  + Записаться_на_урок()
  + Отменить_запись_на_урок()
  + Получить_расписание()
}

class Администратор {
  - Имя: строка
  - Фамилия: строка
  + Составить_урочный_план()
  + Добавить_ученика()
  + Удалить_ученика()
  + Записать_ученика_на_урок()
  + Отменить_запись_ученика_на_урок()
}

class ИнформационнаяСистемаАвтошколы {
  - Список_учеников: список
  - Расписание: список
  - Учебные_планы: список
  + Проверить_доступность_мест()
  + Создать_нового_ученика()
  + Добавить_урок()
  + Удалить_урок()
}

Автоинструктор --* ИнформационнаяСистемаАвтошколы
Ученик --* ИнформационнаяСистемаАвтошколы
Администратор --* ИнформационнаяСистемаАвтошколы
@enduml
