@startuml
actor Ученик
actor Администратор
actor Автоинструктор
participant ИС_автошколы
participant БД_автошколы

Ученик -> ИС_автошколы: Запрос расписания
ИС_автошколы -> БД_автошколы: Получение расписания
БД_автошколы --> ИС_автошколы: Расписание
ИС_автошколы -> Ученик: Отправка расписания

Администратор -> ИС_автошколы: Создать нового ученика
ИС_автошколы -> БД_автошколы: Добавление ученика в базу данных
БД_автошколы --> ИС_автошколы: Ответ об успешном добавлении
ИС_автошколы --> Администратор: Подтверждение успеха операции

Автоинструктор -> ИС_автошколы: Отправить отчет об уроке
ИС_автошколы -> БД_автошколы: Добавить отчет в базу данных
БД_автошколы --> ИС_автошколы: Ответ об успешном добавлении отчета
ИС_автошколы --> Автоинструктор: Подтверждение успеха операции
@enduml
