@startuml
package Пользователь {
  [Ученик]
}

package Администрирование {
  [Администратор]
  [Информационная Система]
}

package Обучение {
  [Автоинструктор]
  [Учебный план]
}

[Ученик] --> [Информационная Система]
[Автоинструктор] --> [Информационная Система]
[Администратор] --> [Информационная Система]
[Информационная Система] --> [Учебный план]
[Информационная Система] --> [База данных]
@enduml
