@startuml "Conceptual data model"

title
Концептуальная модель данных
end title

left to right direction


entity Ученик {
   +ИД_Ученика : integer
   --
   Имя : varchar(50)
   Фамилия : varchar(50)
   Пол : char(1)
   Дата_рождения : date
   Телефон : varchar(20)
   Адрес : varchar(100)
   Электронная_почта : varchar(100)
}

entity Курс {
   +ИД_Курса : integer
   --
   Название : varchar(50)
   Описание : varchar(255)
   Стоимость : decimal(5,2)
   Продолжительность : integer
   Максимальное_количество_учеников : integer
}

entity Инструктор {
   +ИД_Инструктора : integer
   --
   Имя : varchar(50)
   Фамилия : varchar(50)
   Пол : char(1)
   Дата_рождения : date
   Телефон : varchar(20)
   Адрес : varchar(100)
   Электронная_почта : varchar(100)
}

entity Расписание {
   +ИД_Расписания : integer
   --
   Дата_начала : datetime
   Дата_конца : datetime
}

entity Занятие {
   +ИД_Занятия : integer
   --
   Дата_и_время_начала : datetime
   Дата_и_время_конца : datetime
   Продолжительность : integer
}

Ученик --|> Запись_на_курсы : записался на
Курс --|> Запись_на_курсы : обучает
Запись_на_курсы --|> Расписание : назначено на
Расписание --|> Занятие : состоит из
Занятие --|> Инструктор : проводит
Занятие --|> Ученик : посещает
Инструктор --|> Курс : преподаёт
@enduml
