@startuml
node УченикPC {
  artifact Интерфейс_ученика
}
node АдминистраторPC {
  artifact Интерфейс_администратора
}
node АвтоинструкторPC {
  artifact Интерфейс_автоинструктора
}
node Сервер_автошколы {
  node Веб_сервер {
    artifact ИС_автошколы
  }
  database БД_автошколы
}

УченикPC --> Веб_сервер: HTTP
АдминистраторPC --> Веб_сервер: HTTP
АвтоинструкторPC --> Веб_сервер: HTTP
Веб_сервер --> БД_автошколы: JDBC
@enduml
