@startuml Activity diagram for the precedent Provision of driving school services
title
Диаграмма деятельности для прецедента "Оказание услуг автошколы"
end title

|Выбор курса|
start
:Ученик выбирает курс;
if (Доступны курсы?) then (yes)
  :Оплата курса;
  :Заполнение документов;
  |Запись на курсы|
  :Запись ученика на курсы;
  if (Расписание доступно?) then (yes)
    :Выбор инструктора;
    |Открытие курса|
    :Начало занятий;
    :Оценивание успеваемости;
    :Обновление прогресса ученика;
    :Генерация отчетов;
    |Завершение курса|
    :Выдача свидетельства;
  else (no)
    :Попросить дополнительное время;
  endif
else (no)
  :Предложить дополнительные курсы;
endif
stop
@enduml
