@startuml

actor Ученик
participant ИнформационнаяСистема as Система
participant Автошкола

Ученик -> Система: Запросить список курсов
activate Система
Система -> Автошкола: Получить список курсов
activate Автошкола
Автошкола --> Система: Список курсов
deactivate Автошкола
Система --> Ученик: Список курсов
deactivate Система

Ученик -> Система: Выбрать курс
activate Система
Система -> Автошкола: Записать Ученика на курс
activate Автошкола
Автошкола --> Система: Подтверждение записи
deactivate Автошкола
Система --> Ученик: Подтверждение записи
deactivate Система

Ученик -> Система: Проверить расписание
activate Система
Система -> Автошкола: Получить расписание
activate Автошкола
Автошкола --> Система: Расписание занятий
deactivate Автошкола
Система --> Ученик: Расписание занятий
deactivate Система

Ученик -> Система: Записаться на занятие
activate Система
Система -> Автошкола: Записать Ученика на занятие
activate Автошкола
Автошкола --> Система: Подтверждение записи на занятие
deactivate Автошкола
Система --> Ученик: Подтверждение записи на занятие
deactivate Система

Ученик -> Система: Сдать экзамен
activate Система
Система -> Автошкола: Записать Ученика на экзамен
activate Автошкола
Автошкола --> Система: Подтверждение записи на экзамен
deactivate Автошкола
Система --> Ученик: Подтверждение записи на экзамен
deactivate Система

Ученик -> Система: Получить результаты экзамена
activate Система
Система -> Автошкола: Получить результаты экзамена
activate Автошкола
Автошкола --> Система: Результаты экзамена
deactivate Автошкола
Система --> Ученик: Результаты экзамена
deactivate Система
@enduml
