@startuml

left to right direction

[*] --> Главное_меню
Главное_меню --> Выход
state Главное_меню {
  Главное_меню --> Запись_на_урок
  Главное_меню --> Расписание

}
state Запись_на_урок {
  Запись_на_урок --> Категория
  Запись_на_урок --> Дата
  Запись_на_урок --> Назад
}
state Расписание {
  Расписание --> Календарь
  Расписание --> Выбор_урока
  Расписание --> Назад
}

@enduml
