@startuml A model of system precedents

title
Модель системных прецедентов
end title

left to right direction
actor Администратор
actor Инструктор
actor Ученик
rectangle "Система автошколы" {
  (Запись на курсы) <.. Ученик
  (Прохождение курса) <.. Ученик
  (Генерация отчетов) <.> Администратор
  (Генерация отчетов) <.> Инструктор
  (Управление учениками) ..> (Регистрация нового ученика) : "создает"
  (Управление учениками) ..> (Просмотр информации об ученике) : "просматривает"
  (Управление учениками) ..> (Редактирование информации об ученике) : "редактирует"
  (Управление учениками) ..> (Удаление информации об ученике) : "удаляет"
  (Управление курсами) ..> (Создание нового курса) : "создает"
  (Управление курсами) ..> (Просмотр информации о курсе) : "просматривает"
  (Управление курсами) ..> (Редактирование информации о курсе) : "редактирует"
  (Управление курсами) ..> (Удаление информации о курсе) : "удаляет"
  (Управление курсами) ..> (Назначение расписания занятий) : "назначает"
  (Управление инструкторами) ..> (Регистрация нового инструктора) : "создает"
  (Управление инструкторами) ..> (Просмотр информации об инструкторе) : "просматривает"
  (Управление инструкторами) ..> (Редактирование информации об инструкторе) : "редактирует"
  (Управление инструкторами) ..> (Удаление информации об инструкторе) : "удаляет"
  (Запись на курсы) ..> (Просмотр доступных курсов и расписания занятий) : "просмотр"
  (Запись на курсы) ..> (Выбор курса и расписания занятий) : "выбор курса"
  (Запись на курсы) ..> (Запись на курс и оплата) : "запись на курс"
  (Прохождение курса) ..> (Начало курса) : "начало"
  (Прохождение курса) ..> (Посещение занятий) : "посещение"
  (Прохождение курса) ..> (Завершение занятий и оценивание успеваемости) : "оценивание"
  (Завершение занятий и оценивание успеваемости) ..> (Обновление прогресса ученика) : "обновляет прогресс"
  (Генерация отчетов) ..> (Отчет по оценкам успеваемости учеников) : "генерирует"
  (Генерация отчетов) ..> (Отчет по посещаемости занятий учеников) : "генерирует"
  (Генерация отчетов) ..> (Отчет по доходам и расходам автошколы) : "генерирует"
}
@enduml
