@startuml "General use case diagram"
title
Общая диаграмма прецедентов автошколы по обслуживанию ученика
end title

left to right direction

actor Ученик
actor Инструктор
actor Администратор

rectangle "Система автошколы" {
  Ученик -> (Регистрация)
  Ученик -> (Запись на курсы)
  Инструктор -> (Оценивание успеваемости)
  Инструктор -> (Обновление прогресса Ученика)
  Администратор -> (Управление курсами)
  Администратор -> (Управление Инструкторами)
  Администратор -> (Генерация отчетов)
  (Запись на курсы) .> (Оплата) : include
  (Запись на курсы) --> (Выбор расписания)
  (Выбор расписания) --> (Назначение Инструктора)
  (Назначение Инструктора) --> (Начало курса)
  (Начало курса) --> (Оценивание успеваемости)
  (Обновление прогресса Ученика) --> (Генерация отчетов)
}
@enduml
