@startuml
:Автоинструктор: as AI
:Ученик: as U
:Администратор: as A

left to right direction

AI --> (Добавить ученика)
AI --> (Начать урок)
AI --> (Завершить урок)
U --> (Просмотр расписания)
U --> (Записаться на урок)
U --> (Отменить запись на урок)
A --> (Просмотреть учебные планы)
A --> (Просмотреть список учеников)
A --> (Добавить нового ученика)
A --> (Записать ученика на урок)
A --> (Отменить запись ученика на урок)


@enduml
